# Generated by Django 3.1.7 on 2021-03-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=128)),
            ],
            options={
                'db_table': 'Admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='bookID', primary_key=True, serialize=False)),
                ('available', models.IntegerField()),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookauthor',
            fields=[
                ('author', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BookAuthor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('userpassword', models.CharField(db_column='userPassword', max_length=128)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrowreturn',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
                ('extend', models.IntegerField()),
                ('duedate', models.DateField(blank=True, db_column='dueDate', null=True)),
                ('returndate', models.DateField(blank=True, db_column='returnDate', null=True)),
            ],
            options={
                'db_table': 'BorrowReturn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
                ('fineamount', models.IntegerField(db_column='fineAmount')),
            ],
            options={
                'db_table': 'Fine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
                ('paymentdate', models.DateField(db_column='paymentDate')),
                ('paymentamount', models.IntegerField(db_column='paymentAmount')),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservecancel',
            fields=[
                ('userid', models.OneToOneField(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
                ('reservedate', models.DateField(blank=True, db_column='reserveDate', null=True)),
            ],
            options={
                'db_table': 'ReserveCancel',
                'managed': False,
            },
        ),
    ]
