# Generated by Django 3.1.7 on 2021-03-03 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(db_column='bookId', max_length=10, primary_key=True, serialize=False)),
                ('availability', models.IntegerField()),
                ('duedate', models.DateField(blank=True, db_column='dueDate', null=True)),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(db_column='userId', max_length=10, primary_key=True, serialize=False)),
                ('administrative', models.IntegerField()),
                ('fine', models.SmallIntegerField()),
                ('userpassword', models.CharField(blank=True, db_column='userPassword', max_length=10, null=True)),
                ('bookcount', models.SmallIntegerField(db_column='bookCount')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
                ('bookid', models.CharField(db_column='bookId', max_length=10)),
                ('extend', models.IntegerField()),
                ('duedate', models.CharField(db_column='dueDate', max_length=10)),
            ],
            options={
                'db_table': 'Borrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='project.users')),
            ],
            options={
                'db_table': 'Reserved',
                'managed': False,
            },
        ),
    ]
